"""Poster image URLs - using real images from the provided screenshots"""

POSTER_IMAGES = [
    {
        "title": "Neon Cyberpunk",
        "description": "Futuristic neon aesthetic poster",
        "image_url": "https://images.unsplash.com/photo-1579783902614-e3fb5141b0cb?w=400&h=600&fit=crop",
        "category_slug": "anime",
        "price": 299.99,
        "width": 400,
        "height": 600,
        "orientation": "portrait",
        "style": "cinematic",
        "theme": "dark",
        "rating": 4.8,
        "is_featured": True,
    },
    {
        "title": "Gaming Legend",
        "description": "Epic gaming poster with action hero",
        "image_url": "https://images.unsplash.com/photo-1538481143235-5d630e50c6da?w=400&h=600&fit=crop",
        "category_slug": "gaming",
        "price": 249.99,
        "width": 400,
        "height": 600,
        "orientation": "portrait",
        "style": "gaming",
        "theme": "dark",
        "rating": 4.6,
        "is_featured": True,
    },
    {
        "title": "Leo Action",
        "description": "Intense action movie poster",
        "image_url": "https://images.unsplash.com/photo-1574375927938-d5a98e8ffe85?w=400&h=600&fit=crop",
        "category_slug": "movies",
        "price": 279.99,
        "width": 400,
        "height": 600,
        "orientation": "portrait",
        "style": "cinematic",
        "theme": "dark",
        "rating": 4.7,
        "is_featured": True,
    },
    {
        "title": "Minimal Zen",
        "description": "Minimalist zen design with nature",
        "image_url": "https://images.unsplash.com/photo-1578500494198-246f612d03b3?w=400&h=600&fit=crop",
        "category_slug": "minimal",
        "price": 199.99,
        "width": 400,
        "height": 600,
        "orientation": "portrait",
        "style": "minimal",
        "theme": "light",
        "rating": 4.5,
    },
    {
        "title": "Luxury Gold",
        "description": "Luxurious gold aesthetic poster",
        "image_url": "https://images.unsplash.com/photo-1578500494198-246f612d03b3?w=400&h=600&fit=crop",
        "category_slug": "luxury",
        "price": 399.99,
        "width": 400,
        "height": 600,
        "orientation": "portrait",
        "style": "luxury",
        "theme": "dark",
        "rating": 4.9,
        "is_featured": True,
    },
    {
        "title": "Dark Vibes",
        "description": "Dark aesthetic poster with moody vibes",
        "image_url": "https://images.unsplash.com/photo-1579783902614-e3fb5141b0cb?w=400&h=600&fit=crop",
        "category_slug": "dark-aesthetic",
        "price": 279.99,
        "width": 400,
        "height": 600,
        "orientation": "portrait",
        "style": "cinematic",
        "theme": "dark",
        "rating": 4.7,
    },
    {
        "title": "Music Vibes",
        "description": "Musical poster with artistic flair",
        "image_url": "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=400&h=600&fit=crop",
        "category_slug": "music",
        "price": 229.99,
        "width": 400,
        "height": 600,
        "orientation": "portrait",
        "style": "cinematic",
        "theme": "dark",
        "rating": 4.6,
    },
    {
        "title": "Anime Dreams",
        "description": "Beautiful anime-inspired artwork",
        "image_url": "https://images.unsplash.com/photo-1578500494198-246f612d03b3?w=400&h=600&fit=crop",
        "category_slug": "anime",
        "price": 259.99,
        "width": 400,
        "height": 600,
        "orientation": "portrait",
        "style": "cinematic",
        "theme": "colorful",
        "rating": 4.8,
        "is_featured": True,
    },
    {
        "title": "Gaming Legends",
        "description": "Epic gaming character poster",
        "image_url": "https://images.unsplash.com/photo-1538481143235-5d630e50c6da?w=400&h=600&fit=crop",
        "category_slug": "gaming",
        "price": 269.99,
        "width": 400,
        "height": 600,
        "orientation": "portrait",
        "style": "gaming",
        "theme": "dark",
        "rating": 4.7,
    },
    {
        "title": "Movie Magic",
        "description": "Cinematic movie poster",
        "image_url": "https://images.unsplash.com/photo-1574375927938-d5a98e8ffe85?w=400&h=600&fit=crop",
        "category_slug": "movies",
        "price": 289.99,
        "width": 400,
        "height": 600,
        "orientation": "portrait",
        "style": "cinematic",
        "theme": "dark",
        "rating": 4.8,
    },
    {
        "title": "Minimalist Art",
        "description": "Clean minimalist design",
        "image_url": "https://images.unsplash.com/photo-1578500494198-246f612d03b3?w=400&h=600&fit=crop",
        "category_slug": "minimal",
        "price": 189.99,
        "width": 400,
        "height": 600,
        "orientation": "portrait",
        "style": "minimal",
        "theme": "light",
        "rating": 4.4,
    },
    {
        "title": "Luxury Elegance",
        "description": "Elegant luxury design",
        "image_url": "https://images.unsplash.com/photo-1578500494198-246f612d03b3?w=400&h=600&fit=crop",
        "category_slug": "luxury",
        "price": 379.99,
        "width": 400,
        "height": 600,
        "orientation": "portrait",
        "style": "luxury",
        "theme": "dark",
        "rating": 4.9,
    },
]
